# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb0be6a2b9c4877acab5b607786e29017803360a46596e0ee29dab8ae7bd52a5caeb54cb3018f1300a35edb865413b489eb339c716a736e62da47a83bbfb43a8

test:
  secret_key_base: 28046b6a752107a60b81c023bdb84ca9593db6f472870ab581e12e82308b1a28bbdcb8edbfac7c682b671fb078e17c6ceb689effd77d68af1e40b5b4733ee858

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
